sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t slickrighty/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true slickrighty/react-test npm test

after_success:
  - docker build -t slickrighty/multi-client ./client
  - docker build -t slickrighty/multi-nginx ./nginx
  - docker build -t slickrighty/multi-server ./server
  - docker build -t slickrighty/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push slickrighty/multi-client
  - docker push slickrighty/multi-nginx
  - docker push slickrighty/multi-server
  - docker push slickrighty/multi-worker
 
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-531282716202
  bucket_path: docker-multi
  edge: true 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
